// Code generated by mockery 2.7.5. DO NOT EDIT.

package mocks

import (
	logger "bitbucket.org/kawancicil/core-library/logger"
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// Logger is an autogenerated mock type for the Logger type
type Logger struct {
	mock.Mock
}

// BuildLogger provides a mock function with given fields: ctx, logType, statusCode, message
func (_m *Logger) BuildLogger(ctx *gin.Context, logType string, statusCode int, message string) logger.LoggerPayload {
	ret := _m.Called(ctx, logType, statusCode, message)

	var r0 logger.LoggerPayload
	if rf, ok := ret.Get(0).(func(*gin.Context, string, int, string) logger.LoggerPayload); ok {
		r0 = rf(ctx, logType, statusCode, message)
	} else {
		r0 = ret.Get(0).(logger.LoggerPayload)
	}

	return r0
}
